### ISSUE TITLE
Scenario isolation does not work

### ISSUE THREAD

**Issue by romanzks** [soulcodex/laravel-behat#1]
The new scenario saves the state of the previous one, which shouldn't be

**Comment by soulcodex** [comment]
Hi @romanzks can you tell me which state isn't refreshed? Database, Application kernel or any other ?

Best

**Comment by romanzks** [comment]
If I understand correctly, this is Application kernel.

For example, in the first scenario, I log in as a user. in the second, I have to be not logged, but I remain logged in.

**Comment by soulcodex** [comment]
Great at least one clue, let me check it this weekend to brings you a fast solution 😉 

Are you currently extending from the package base context? 👀

Thank you very much for your great first issue

**Comment by romanzks** [comment]
Thanks for the great extension. After the original extension stopped supporting Laravel, your extension became a great replacement. This is my config file, maybe it will be useful.

```yaml
default:
  extensions:
    Soulcodex\Behat:
      kernel:
        bootstrap_path: '/bootstrap/app.php'
        environment_path: '.env.behat'
    Behat\MinkExtension:
      base_url: https://example.test/
      default_session: laravel
      laravel: ~

  suites:
    default:
      contexts:
        - FeatureContext
      paths:
        - "%paths.base%/features"
```

**Comment by soulcodex** [comment]
One question more, can you share me your FeatureContext file here please?🙏🙏

**Comment by romanzks** [comment]
The bug reproduces even with an empty FeatureContext class and such a scenario.

```php
use Behat\Behat\Context\Context;
use Behat\MinkExtension\Context\MinkContext;

class FeatureContext extends MinkContext implements Context
{
}
```

```gherkin
Feature: Sign in to the website
    I need to be able to log in to the website

    Scenario: Log in with email and password
      Given I am on "/login"
       When I fill in the following:
          | email    | admin@admin.com |
          | password | password        |
       And I press "Login"
      Then I should be on "/admin"
       And I should see "Hello Admin"

    Scenario: Log in with bad credentials
      Given I am on "/login"
       When I fill in the following:
          | email    | admin@admin.com |
          | password | wrong_password  |
        And I press "Login"
       Then I should be on "/login"
```

I am getting an error on the second scenario. The user does not see the login field, because already authorized.

**Comment by romanzks** [comment]
My guess is that the issue may lie somewhere here **KernelAwareInitializer**

```php
    public function rebootKernel()
    {
        if ($this->context instanceof KernelAwareContext) {
            $kernelConfig = $this->kernelConfig();
            $this->app->flush();

            $laravel = new LaravelEnvironmentArranger(
                $kernelConfig->basePath(),
                $kernelConfig->environmentFile()
            );

            $this->context->session('laravel')
                ->getDriver()
                ->reboot($this->app = $laravel->boot($kernelConfig->toArray()));
        }
    }
```

**Comment by romanzks** [comment]
It is not possible to reset the session even in manual mode, using a hook.

```php
/**
 * @BeforeScenario
 */
public function before(BeforeScenarioScope $event)
{
    $this->getSession()->restart();
}
```

**Comment by soulcodex** [comment]
Try to extend from Soulcodex\Behat\Addon\Context as well and run again the test to see what's happen 😁

**Comment by romanzks** [comment]
Can you please tell me how to use the methods of the MinkContext class in this case?

**Comment by soulcodex** [comment]
I have to improve this, let me work on this and I will keep you updated through this issue 😁😇

**Comment by romanzks** [comment]
Ok. I think i figured out how to do it
```yaml
  suites:
    default:
      contexts:
        - Behat\MinkExtension\Context\MinkContext
        - FeatureContext
      paths:
        - "%paths.base%/features"
```
But now I am getting a new error on the second scenario.
```
Scenario: Log in with bad credentials # features/login.feature:17
    Given I am on "/login"              # Behat\MinkExtension\Context\MinkContext::visit()
      Target [Illuminate\Contracts\Http\Kernel] is not instantiable. (Illuminate\Contracts\Container\BindingResolutionException)
```
